# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalrequirement',
            name='effor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requirement',
            name='effor',
            field=models.IntegerField(default=0),
        ),
    ]
