# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('projects', models.ManyToManyField(to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
