# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20171222_2204'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='power',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='stakeholders',
            field=models.ManyToManyField(through='projects.Power', to='clients.Client'),
        ),
    ]
