# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20171217_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalrequirement',
            old_name='effor',
            new_name='effort',
        ),
        migrations.RenameField(
            model_name='requirement',
            old_name='effor',
            new_name='effort',
        ),
    ]
