# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_projects'),
        ('projects', '0003_auto_20171217_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='assessments',
            field=models.ManyToManyField(through='projects.Assessment', to='clients.Client'),
        ),
    ]
