# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_requirement_assessments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
