# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20171217_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='last_released',
            field=models.BooleanField(default=False),
        ),
    ]
