# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('requirements', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assessments',
            field=models.ManyToManyField(through='requirements.Assessment', to='clients.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(through='projects.Power', to='projects.Project'),
        ),
    ]
