# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_requirement_assessments'),
        ('clients', '0002_client_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assessments',
            field=models.ManyToManyField(through='projects.Assessment', to='clients.Client'),
        ),
    ]
